### ISSUE TITLE
От Бородина

### ISSUE THREAD

**Issue by wats-up** [geekhubshow/yce_systems#1]
Действуй в нескольких ветках. Так то гит для этого и создан: система регистрации версий, то есть облако, где одновременно разрабатывать могут много людей. Обычно в серьезных проектах каждый создает свою ветку и когда надо отправляют запрос на копирование кода в основу, а мид или сеньор проверяют, если какие то неожиданные несоответствия с прошлым кодом.

**Comment by geekhubshow** [comment]
ок
